### ISSUE TITLE
Swiping between slides not working with autoWidth on iOS

### ISSUE THREAD

**Issue by roahes89** [ganlanyuan/tiny-slider#315]
__Issue description__:  Swiping between slides not working with autoWidth on iOS

__Demo link/slider setting__:   http://ganlanyuan.github.io/tiny-slider/demo/#autoWidth_wrapper
On an iOS device, swiping on the images does nothing even though mouseDrag is true? I've done something similar but within the demos it doesn't work either.

_Tiny-slider version_:  2.8.7
_Browser name && version_:  iOS Safari 12
_OS name && version_:   iPhone

**Comment by deomsj** [comment]
I am also having trouble with this. Any help or advice on this would be super helpful!

**Comment by ganlanyuan** [comment]
The issue seems mainly happen in webkit browsers. 
Firefox works fine.
I'm still searching for the reason.

**Comment by deomsj** [comment]
@ganlanyuan thanks for looking into this! 

Few things that I've noticed in trying to understand what might be going on here:
 - mousedrag and appears to be working correctly in all desktop browsers
 - in iOS, swiping works inconsistently across refreshing same page
 - I am seeing the same behavior with `autoWidth` and `fixedWidth`. 

In [my stackblitz example](https://stackblitz.com/edit/tiny-slider-ios-therapy), I am seeing errors that lead me to believe this might be related to the `cancelAnimationFrame` implementation.

![stackblitz erros](https://user-images.githubusercontent.com/20070114/47659433-58a51e80-db6b-11e8-994d-87193d15d766.PNG)

in iOS, I am getting the following error: 
![tiny-slider-ios](https://user-images.githubusercontent.com/20070114/47659676-d701c080-db6b-11e8-87bf-8ca1a6aa8000.jpg)

Hope this is helpful. Thanks for your support with this! I'll continue to share more info if I make any more discoveries...

**Comment by deomsj** [comment]
so it looks like the errors that I described above may be specific to tiny-slider's performance in the stackblitz environment. When testing in code-sandbox, I am not able to replicate the bugs above on desktop or iOS when using fixedWidth. 

In [my CodeSandbox example](https://codesandbox.io/embed/2wqmzoyj8r), I am seeing the carousels inconsistently respond to swiping in iOS when the carousels are initialized with autoWidth. To see this behavior on an iOS device go to [https://2wqmzoyj8r.codesandbox.io/](https://2wqmzoyj8r.codesandbox.io/) using chrome or safari

As far as i can tell, autoWidth works great on desktop and on iOS firefox.

**Comment by niroj08** [comment]
> The issue seems mainly happen in webkit browsers.
> Firefox works fine.
> I'm still searching for the reason.

not working in firefox as well..

**Comment by ganlanyuan** [comment]
It turns out to be a CSS issue. Should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/c4e16b6f32acecd6b01e3f162af97a8e87eed35f).

**Comment by deomsj** [comment]
thanks for your efforts in running this down @ganlanyuan!

**Comment by jsunsawyer** [comment]
I'm experiencing this exact issue with tiny slider 2.9.1.

**Comment by ggsandro** [comment]
Still experiencing this issue

**Comment by ThaoD5** [comment]
Confirming this is still happening on some iphones
Checked on iphone8 (ios12) iphone 8 (ios13) iphone XS (ios13) iphone XS (ios12) but somehow seemed to work on iphone 11 (ios13)

**Comment by skillwork-mdimitrov** [comment]
Any updates on this? Still happening.
