### ISSUE TITLE
In mode: 'gallery', and autoplay: true, it only repeats three times the cycle of images.

### ISSUE THREAD

**Issue by nandes2062** [ganlanyuan/tiny-slider#88]
__Issue description__:  
In **mode: 'gallery'** , and **autoplay: true**, it only repeats three times the cycle of images,
after the three repetitions it becomes totally static without autoplay

_Tiny-slider version_:   v2.2.4
_Browser name && version_:  Chrome 61
_OS name && version_:   Ubuntu 16.04

**Comment by kebbet** [comment]
Can confirm bug in
Safari 11.0
MacOS High Sierra (10.13)

**Comment by ganlanyuan** [comment]
Sorry for the late response, this should be fixed in v2.2.5

**Comment by ganlanyuan** [comment]
Closed due to no activity.
Feel free to reopen it.

**Comment by nandes2062** [comment]
Thank you very much, if it is solved in v2.2.5

**Comment by kyleaffolder** [comment]
I am still seeing this as a bug (in latest plugin code). Came across this issue today while trying to implement the slider into my site. I'll try and document what's going on.

__Issue description__:  
It appears that when the browser is at a larger breakpoint and the slider is set to `mode: 'gallery'`, then the slider will only page (repeat) a few times before breaking to only displaying one slide at a time. For example, viewing my Fiddle at a browser viewport of 1200px should display a total of 5 slides, paging 5 at a time. (`slideBy: 'page', items: 5`) When the slider pages 3 times it then breaks. (You can speed up the autoplay by using the nav.)

Seems like a bug. The only thing I've been able to do is force my client to create a minimum of 12 slides. For whatever reason, this seems to "fix" the issue.

__Demo link/slider setting__:   
[jsFiddle](https://jsfiddle.net/7zq0s8xm/)

_Tiny-slider version_:   2.5.0
_Browser name && version_:  Chrome 63.0.3239.132 (Official Build) (64-bit)
_OS name && version_:   macOS High Sierra 10.13.2
